### ISSUE TITLE
Community Meeting January 24th, 2024

### ISSUE THREAD

**Issue by lcarva** [enterprise-contract/community#24]
## Overview
At 10am Eastern, 7am Pacific, 2pm UTC; [find your time](https://www.timeanddate.com/worldclock/converter.html?iso=20210518T140000&p1=1440&p2=4826&p3=234&p4=195)

Video call link: [https://meet.google.com/ved-ivnv-aen](https://meet.google.com/ved-ivnv-aen?hs=122&authuser=0)
dial-in: (US) +1 409-444-2447‬
PIN: ‪873 550 579#‬
More phone numbers: [tel.meet/ved-ivnv-aen?pin=7872592963542&hs=1](https://tel.meet/ved-ivnv-aen?pin=7872592963542&hs=1)

**Add topics you'd like to discuss below!**

**Comment by lcarva** [comment]
I'd like to discuss "acceptable bundles" as described [here](https://enterprisecontract.dev/docs/ec-policies/acceptable_bundles.html).

> The list of acceptable bundles is time based. A bundle that is acceptable today is not necessarily acceptable tomorrow. The list below may contain bundles that are "too old" and no longer acceptable. The reason for this behavior is to allow users a certain period of time to upgrade to a newer bundle.

The concept of entries being "too old" is confusing, making it hard to get the implementation right, and even to explain how it is supposed to work for users.

To further complicate things, the complete feature is implemented partially in ec-cli and partially in ec-policies.

Maybe it's time to find an alternate approach?

(Also somewhat related to https://github.com/enterprise-contract/ec-cli/issues/1291)

**Comment by mbestavros** [comment]
If we have time, it might be good to discuss how we're tackling `effective_on` in `rule_data.yml`.

**Comment by robnester-rh** [comment]
Meeting recording: https://drive.google.com/file/d/1hZKzVfxk8_GANKn_8vRTpo0dIhFYW1Gc/view?usp=drive_link
